version: 2
builds:
- id: malwatch
  binary: malwatch
  main: ./cmd/malwatch
  env:
    - CGO_ENABLED=1
    - CC=/usr/bin/x86_64-linux-musl-gcc
  ldflags:
    - "-w -s"
    - "-linkmode external"
    - "-extldflags '-static -I./third_party/mimalloc/inc -L./third_party/mimalloc/lib -lmimalloc'"
    - "-X github.com/defended-net/malwatch/pkg/boot/env.ver={{.Version}}"
  flags:
    - -trimpath
  goos:
    - linux
  goarch:
    - amd64
- id: malwatch-monitor
  binary: malwatch-monitor
  main: ./cmd/malwatch-monitor
  env:
    - CGO_ENABLED=1
    - CC=/usr/bin/x86_64-linux-musl-gcc
  ldflags:
    - "-w -s"
    - "-linkmode external"
    - "-extldflags '-static -I./third_party/mimalloc/inc -L./third_party/mimalloc/lib -lmimalloc'"
    - "-X github.com/defended-net/malwatch/pkg/boot/env.ver={{.Version}}"
  flags:
    - -trimpath
  goos:
    - linux
  goarch:
    - amd64

archives:
  - format: tar.gz

changelog:
  sort: asc
  groups:
    - title: "Sec"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 100
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 200
    - title: "Fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 300
    - title: "Refactors"
      regexp: '^.*?refactor(\(.+\))??!?:.+$'
      order: 400
    - title: "Tests"
      regexp: '^.*?test(\(.+\))??!?:.+$'
      order: 500
    - title: "CI"
      regexp: '^.*?ci(\(.+\))??!?:.+$'
      order: 600
    - title: "Build"
      regexp: '^.*?build(\(.+\))??!?:.+$'
      order: 700
    - title: "Dependencies"
      regexp: '^.*?dep(\(.+\))??!?:.+$'
      order: 800
    - title: Other work
      order: 9999

release:
  extra_files:
  - glob: ./LICENSE
  - glob: ./README.md
  footer: >-

    ---

    Please review our [documentation](https://docs.defended.net/malwatch).
