name: race

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  race:
    name: race
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: tests with race detector
        env:
          JSON_USER: ${{ secrets.JSON_USER }}
          JSON_PASS: ${{ secrets.JSON_PASS }}
          PD_TOKEN: ${{ secrets.PD_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SMTP_HOSTNAME: ${{ secrets.SMTP_HOSTNAME }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          SUBMIT_ENDPOINT: ${{ secrets.SUBMIT_ENDPOINT }}
          SUBMIT_KEY: ${{ secrets.SUBMIT_KEY }}
          GIT_0_USER: ${{ secrets.GIT_0_USER }}
          GIT_0_TOKEN: ${{ secrets.GIT_0_TOKEN }}
          GIT_0_URL: ${{ secrets.GIT_0_URL }}
        run: |
          pkgs=$(go list ./... | grep -v '/yr' || true)
          [ -n "$pkgs" ] && go test -race $pkgs
